on:
  push:
    branches: [ rebase ]
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20220130

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: apt update && apt upgrade -y
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y git bison flex libxml2 libssl-dev bc zip default-jre python3 python3-pip wget curl cpio bash python2
      - run: bash build.sh
    env:
        token: ${{ secrets.TOKEN }}
        chat_id: ${{ secrets.CHAT_ID }}
